version: '3'

services:
  web:
    build: 
      context: .
      args:
        - POSH_THEME=jandedobbeleer
        - TZ=Asia/Bahrain # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

    working_dir: /app

    volumes:
      - "..:/app"

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/bash -c "while sleep 1000; do :; done"